### ISSUE TITLE
feat: retrieve BioSample metadata?

### ISSUE THREAD

**Issue by theosanderson** [rpetit3/fastq-dl#10]
Thanks so much for this tool! Just wanted to capture a potential feature in case it is of any interest to you. I downloaded all the fastq's associated with a BioProject, which was really useful. But I realised I also needed the metadata associated with each BioSample. From my POV if there had been a way to get that in the run-info JSON it could have been useful.

(In my case I ended up doing this with this script - https://github.com/theosanderson/add_biosample_metadata_to_fastqdl_json/blob/main/add_biosample_metadata_to_fastqdl_json.py )

Feel free to close without action, thanks again.

**Comment by mbhall88** [comment]
I agree this information can be useful, but I am torn as to whether this is "feature bloat". We would then need to maintain metadata retrieval when tools like https://github.com/saketkc/pysradb are much more feature-rich for retrieving metadata from all types of accessions.

@rpetit3 what do you think?

**Comment by theosanderson** [comment]
Nice - I wasn't aware of pysradb! Very happy with that answer

**Comment by rpetit3** [comment]
Thanks for reaching out! I agree with @mbhall88 on this one, would prefer to keep it simple and let user's handle the extra metadata. Either using tools like your own, or others, that are much better suited for metadata extraction then fastq-dl will ever be.
