### ISSUE TITLE
Invalid search terms after ENA API update

### ISSUE THREAD

**Issue by mbhall88** [rpetit3/fastq-dl#15]
The [ENA API changed yesterday](https://docs.google.com/document/d/1RPHmK8Pvm9UxSa21Ej3MkGoGYO9baSxwxk_dOuWWyNE/edit?usp=sharing) and the following fields are no longer valid: `cram_index_ftp,cram_index_aspera,cram_index_galaxy`.

> cram_index_* : removed. Instead index (crai/bai) files are available with the respective data files e.g. fastq_ftp, submitted_ftp

Using v1.1.1 I get the following error message

```
2023-05-03 06:13:13:root:ERROR - There was an issue querying ENA, exiting...
2023-05-03 06:13:13:root:ERROR - STATUS: 400
2023-05-03 06:13:13:root:ERROR - TEXT: Invalid fieldName(s) supplied: cram_index_ftp,cram_index_aspera,cram_index_galaxy
```

**Comment by mbhall88** [comment]
I'm testing out a fix on my branch at the moment

**Comment by rpetit3** [comment]
@mbhall88 Here's the current available fields: https://www.ebi.ac.uk/ena/portal/api/v2.0/searchFields?dataPortal=ena&format=tsv&result=read_run

We could potentially ping ENA each time to get the available list of columns. I think we'll find most of the fields are blank though.

I think there are a few options here.

1. Leave as is, only removing fields that no longer exist
2. Ping ENA  each execution, build current list of fields, if not possible fall back on hard coded fields
3. Take the list now, and hard code them

I think 2 would be possible, but it might be annoying if you end up getting temp banned (not sure it would be possible to even acheive this)

For #2, I would probably filter out all empty columns and notify the user (e.g. the following fields were excluded: cell_line, etc...). The user would have an option to skip this and output all non-empty columns

**Comment by mbhall88** [comment]
I agree option 2 would be the more complete solution. However, I noticed there are a number of missing fields. Maybe most importantly, that list doesn't have `fastq_ftp`, which we rely on for ENA download. This is a valid search term still though (my testing of option 1 was successful). 

Looking through the [portal API docs](https://docs.google.com/document/d/1CwoY84MuZ3SdKYocqssumghBF88PWxUZ/edit#heading=h.ag0eqy2wfin5), we could just use the 'all' value for fields? If I do that, I get the following fields

```
run_accession	submission_accession	library_min_fragment_size	bam_md5	assembly_software	library_prep_longitude	library_selection	pcr_isolation_protocol	chip_protocol	sequencing_primer_provider	serotype	environment_feature	last_updated	submitted_galaxy	extraction_protocol	germline	secondary_project	culture_collection	submission_tool	sra_bytes	read_strand	rna_purity_280_ratio	hi_c_protocol	collected_by	submitted_ftp	restriction_enzyme_target_sequence	isolate	fastq_bytes	instrument_platform	variety	sequencing_date_format	temperature	sra_aspera	ecotype	submitted_aspera	sampling_campaign	bam_ftp	tissue_lib	environmental_sample	control_experiment	sex	submitted_md5	checklist	fastq_galaxy	library_gen_protocol	specimen_voucher	library_prep_latitude	submitted_bytes	taxonomic_identity_marker	run_date	country	ncbi_reporting_standard	sample_description	experiment_title	sra_galaxy	project	sample_prep_interval	fastq_md5	sample_accession	secondary_study_accession	experimental_protocol	read_count	study_title	bio_material	rna_prep_5_protocol	host_body_site	local_environmental_context	assembly_quality	sample_capture_status	sample_title	host_genotype	host_phenotype	environmental_medium	cultivar	instrument_model	faang_library_selection	target_gene	bam_bytes	library_max_fragment_size	experiment_target	sequencing_date	nominal_sdev	chip_ab_provider	environment_material	host_tax_id	sample_material	sample_storage_processing	sra_md5	cell_type	fastq_ftp	sample_prep_interval_units	broker_name	sub_strain	base_count	library_strategy	restriction_site	serovar	investigation_type	location	library_source	sra_ftp	library_layout	experimental_factor	sequencing_primer_catalog	environment_biome	rna_purity_230_ratio	dnase_protocol	dev_stage	library_prep_date_format	bam_aspera	binning_software	datahub	rna_integrity_num	library_prep_date	location_start	marine_region	aligned	file_location	sample_collection	chip_target	nominal_length	broad_scale_environmental_context	sequencing_location	completeness_score	lon	fastq_aspera	host_sex	library_pcr_isolation_protocol	sample_alias	mating_type	sub_species	contamination_score	run_alias	restriction_enzyme	depth	submitted_read_type	library_construction_protocol	host_growth_conditions	collection_date	experiment_alias	host_gravidity	center_name	identified_by	cell_line	sampling_site	host	library_name	tag	first_created	lat	strain	experiment_accession	scientific_name	host_status	tax_id	study_accession	submitted_format	submitted_host_sex	bisulfite_protocol	altitude	rt_prep_protocol	bam_galaxy	accession	secondary_sample_accession	sample_storage	cage_protocol	sampling_platform	taxonomic_classification	location_end	protocol_label	elevation	salinity	sequencing_method	sequencing_primer_lot	first_public	transposase_protocol	study_alias	library_prep_location	rna_prep_3_protocol	ph	sequencing_longitude	tissue_type	isolation_source
```

**Comment by rpetit3** [comment]
`all` is the way to go, that didn't exist ages of (or if it did was undocumented). Nice find!
