### ISSUE TITLE
Question: checksum

### ISSUE THREAD

**Issue by MostafaYA** [rpetit3/fastq-dl#21]
Hi, very nice tool. 
Just a question, does `fastq-dl `examine the md5 of downloaded reads or others to verify if the download was not corrupted for any reasons? 
Thanks, Mostafa

**Comment by MostafaYA** [comment]
thanks for the clarification.

**Comment by rpetit3** [comment]
Hi @MostafaYA 

I'm going to go ahead and close this, please fill free to reopen!

Cheers,
Robert

**Comment by mbhall88** [comment]
@rpetit3 I wonder if maybe there should be two 'force' style options.

One to force overwriting existing files - but still checks the md5 matches - and another to ignore md5s. I have an example where the file exists, but it is truncated, and thus the md5 doesn't match, but fastq-dl doesn't overwrite it. I know I can use `--force` here, but then I don't get the security of the md5 check.

So with none of those options, the behaviour would be that the md5 of an existing file would be checked to see if it matches what I have. With `--force` it would re-download the file, checking the md4. With `--ignore` it would download the file if it doesn't exist and not check the md5, or not check the md5 of an existing file. With both `--force` and `--ignore` you re-download and don't check md5.
