### ISSUE TITLE
getting technical reads on fastq-dl

### ISSUE THREAD

**Issue by reetm09** [rpetit3/fastq-dl#24]
Hi,

I'm trying to extract scRNA-seq fastq files and this tool works great! However, I was wondering if there was an option to get all the files in a paired-end sample? I only am getting one file back (SRR23891520.fastq.gz) but I believe I should get 2. There is a similar option on `fasterq-dump` by adding the "--include-technical" tag but I'd rather use `fastq-dl` and was curious if there was a way to do that through this package?

This is the command I ran:
`fastq-dl --provider SRA  -a SRR23891520`

Thanks so much for your help!

**Comment by mranjan1** [comment]
Can you try the command below and see if it works?

fastq-dl --provider ENA -a SRR23891520

**Comment by mbhall88** [comment]
According to the SRA there is only one fastq https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR23891520&display=metadata

So this is either a problem from the submitter or the SRA? They seem to be very recently submitted, sometimes there can be a lag in SRA/ENA so maybe check again in a few days?

**Comment by reetm09** [comment]
Hi @mranjan1 and @mbhall88,

Thanks so much! I tried the command but only got one file since I think there might be a lag in the upload of data, as you said. I was also wondering, if I did "--group-by-sample" how are the fastq's merged? Is it just concatenated at the end of the previous fastq, and is there a way to split it after the download?

Thanks!

**Comment by rpetit3** [comment]
Hi @reetm09 

`--group-by-sample` will take multiple Run accessions associated with a single Biosample accession and merge them into a single FASTQ. You are correct they are merged by concatenating the FASTQs together.

If there was a downstream need to split them afterwards, I would recommend against using `--group-by-sample` from the start.

There is usually a 1-2 week delay in syncing between ENA and SRA.

As to your original question about `--include-technical`, that would certainly be possible as an optional input. However, can you share some examples where you would use this? (I don't have any use cases in by day job).

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi All!

I'm going to go ahead and close this, as I think things were resolved. Please feel free to reopen if not.

Cheers,
Robert
