### ISSUE TITLE
Verison is SLOOOOW

### ISSUE THREAD

**Issue by mbhall88** [rpetit3/fastq-dl#31]
Took 13 seconds on my system to get `fastq-dl --version` to complete. Is this just me?

**Comment by mbhall88** [comment]
My assumption is that this is because of rick_click?

**Comment by rpetit3** [comment]
Here's what I get

```
time fastq-dl --version
fastq-dl, version 2.0.4

real    0m0.411s
user    0m1.352s
sys     0m0.064s
```

**Comment by mbhall88** [comment]
Huh. So something is going on with my system them
