### ISSUE TITLE
Error using fastq-dl on HPC Cluster with Sturm

### ISSUE THREAD

**Issue by sven1990** [rpetit3/fastq-dl#4]
Hi, 

I am trying to use fastq-dl on a HPC cluster with slurm. 
However, the download fails due to the wget error Exit Code 4.

If I try it on the head node without job submission the tool and wget works fine. 

I've read that HPC cluster nodes often require a proxy for wget. 

Is there a wait to use fastq-dl on a cluster node?

**Comment by rpetit3** [comment]
Hello @sven1990 !

Can you confirm whether or not the compute nodes have internet access or not?

Cheers,
Robert

**Comment by sven1990** [comment]
Hi Robert, 

I talked to the cluster service unit and they suggest to just change ftp:// to https:// in the wget command that is run by fastq-dl. 

I changed that in the script and it downloaded 11 Gb for the first file but now the processes are „sleeping“. 

Is there anything in the script that can be adjusted to make this work better?

Best 

Sven

**Comment by rpetit3** [comment]
Hmm I had to change to ftp for ENA (https://github.com/rpetit3/fastq-dl/releases/tag/v1.0.6).

You can always try using SRA for the downloads

**Comment by rpetit3** [comment]
Hi @sven1990 

Did you by chance make progress on this?

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @sven1990, 

Going to go ahead and close this issue, please feel free to reopen!

Robert
