### ISSUE TITLE
pigz error runnning multiple downloads in same directory

### ISSUE THREAD

**Issue by kcamnairb** [rpetit3/fastq-dl#6]
Hi,

I have been using fastq-dl to download multiple SRA runs in the same directory. The command I used was `fastq-dl --outdir data/tmp_data/fastq --cpus 6 SRR16156357 SRA`  and I'm getting an error `bash -c 'pigz --force -p 6 -n --fast *.fastq'
Standard error:
pigz: skipping: SRR21821652_1.fastq does not exist
` .  This happened in several other downloads. You can see that the SRA number in the error is different than the one in my command. It looks like the wildcard is including fastqs from other downloads. Would it be difficult to specify the actual fastq files instead of using the wildcard? Or, maybe I should just stick to one download at a time.

Thanks,
Brian

**Comment by rpetit3** [comment]
Hi @kcamnairb 

Apologies for the delay, but this is not fixed in v1.2.0 (https://github.com/rpetit3/fastq-dl/releases/tag/v1.2.0)

Thank you very much for letting me know!
Robert
